name: Node.js CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Run Prettier
        run: npm run format .

      - name: Build (if applicable)
        run: npm run prepare --if-present

      - name: Run tests with Firebase Emulator
        env:
          FIRESTORE_EMULATOR_HOST: "localhost:8080"
        run: |
          firebase emulators:start --only firestore &
          sleep 10
          npm test
